//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pharmacy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PharmacyCourseProjectEntities : DbContext
    {
        public PharmacyCourseProjectEntities()
            : base("name=PharmacyCourseProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analogs> Analogs { get; set; }
        public virtual DbSet<Discount> Discount { get; set; }
        public virtual DbSet<Drugs> Drugs { get; set; }
        public virtual DbSet<Medications> Medications { get; set; }
        public virtual DbSet<PharmacologicalGroup> PharmacologicalGroup { get; set; }
        public virtual DbSet<Producers> Producers { get; set; }
    }
}
